URLS = [
    "https://jobs.dou.ua/vacancies/?category=Python&exp=0-1",
    "https://jobs.dou.ua/vacancies/?category=Python&exp=1-3",
    "https://jobs.dou.ua/vacancies/?category=Python&exp=3-5",
    "https://jobs.dou.ua/vacancies/?category=Python&exp=5plus",
]

TECHNOLOGIES = [
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "Pyramid",
    "Tornado",
    "Bottle",
    "AWS",
    "RoboDK",
    "API",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Celery",
    "Redis",
    "RabbitMQ",
    "Apache Kafka",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MongoDB",
    "Elasticsearch",
    "SQLAlchemy",
    "Peewee",
    "Jenkins",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Sentry",
    "New Relic",
    "Grafana",
    "Prometheus",
    "pytest",
    "unittest",
    "coverage.py",
    "tox",
    "requests",
    "httpx",
    "aiohttp",
    "BeautifulSoup",
    "Scrapy",
    "Pytest-Django",
    "Flask-RESTful",
    "DRF",
    "Pydantic",
    "Marshmallow",
    "OpenCV",
    "TensorFlow",
    "PyTorch",
    "scikit-learn",
    "Keras",
    "NLTK",
    "spaCy",
    "Jupyter",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Dash",
    "Pygame",
    "Pandas",
    "NumPy",
    "SciPy",
    "SymPy",
    "ML",
    "GIT"
]

EXPERIENCE_LEVELS = {
        "0-1": "Junior",
        "1-3": "Middle",
        "3-5": "Senior",
        "5plus": "Lead",
    }

